<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="AspNetCore.HealthChecks.NpgSql" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="prometheus-net.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AGS.SmartShift.Application\AGS.SmartShift.Application.csproj" />
    <ProjectReference Include="..\AGS.SmartShift.Infrastructure\AGS.SmartShift.Infrastructure.csproj" />
  </ItemGroup>

</Project>
