// <auto-generated />
using System;
using AGS.SmartShift.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AGS.SmartShift.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SmartShiftDbContext))]
    [Migration("20260520041208_AddFlightRegistrationAndCarry")]
    partial class AddFlightRegistrationAndCarry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Attendance.AttendanceGpsPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("AttendanceRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("attendance_record_id");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<double>("Lng")
                        .HasColumnType("double precision")
                        .HasColumnName("lng");

                    b.HasKey("Id")
                        .HasName("pk_attendance_location_samples");

                    b.HasIndex("AttendanceRecordId", "AtUtc")
                        .HasDatabaseName("ix_attendance_location_samples_attendance_record_id_recorded_at");

                    b.ToTable("attendance_location_samples", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Attendance.AttendanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double?>("CheckInLat")
                        .HasColumnType("double precision")
                        .HasColumnName("check_in_lat");

                    b.Property<double?>("CheckInLng")
                        .HasColumnType("double precision")
                        .HasColumnName("check_in_lng");

                    b.Property<DateTime>("CheckInUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_in_at");

                    b.Property<DateTime?>("CheckOutUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_out_at");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double?>("CurrentLat")
                        .HasColumnType("double precision")
                        .HasColumnName("current_lat");

                    b.Property<double?>("CurrentLng")
                        .HasColumnType("double precision")
                        .HasColumnName("current_lng");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("GeoNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("geo_note");

                    b.Property<bool>("GeoSimulated")
                        .HasColumnType("boolean")
                        .HasColumnName("geo_simulated");

                    b.Property<bool>("InZone")
                        .HasColumnType("boolean")
                        .HasColumnName("in_zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_attendance_records");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_attendance_records_employee_id");

                    b.ToTable("attendance_records", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Attendance.WorkZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("PolygonJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("polygon_json");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_work_zones");

                    b.HasIndex("SiteId", "IsActive")
                        .HasDatabaseName("ix_work_zones_site_id_is_active");

                    b.ToTable("work_zones", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Audit.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EmployeeCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("employee_code");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("http_method");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("path");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<Guid?>("UserAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_events");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("ix_audit_events_occurred_at");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Identity.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AllowedRoles")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("allowed_roles_json")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_departments");

                    b.HasIndex("SiteId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_departments_site_id_code");

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Identity.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uuid")
                        .HasColumnName("manager_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_employees");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_employees_code");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_employees_department_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_employees_name");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserAccountId", "ExpiresAtUtc")
                        .HasDatabaseName("ix_refresh_tokens_user_id_expires_at");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Identity.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("timezone");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sites");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_sites_code");

                    b.ToTable("sites", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Identity.SystemPermission", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("module");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameVi")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name_vi");

                    b.HasKey("Code")
                        .HasName("pk_system_permissions");

                    b.ToTable("system_permissions", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Identity.SystemRole", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameVi")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name_vi");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Code")
                        .HasName("pk_system_roles");

                    b.ToTable("system_roles", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Identity.SystemRolePermission", b =>
                {
                    b.Property<string>("RoleCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role_code");

                    b.Property<string>("PermissionCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("permission_code");

                    b.HasKey("RoleCode", "PermissionCode")
                        .HasName("pk_system_role_permissions");

                    b.HasIndex("PermissionCode")
                        .HasDatabaseName("ix_system_role_permissions_permission_code");

                    b.ToTable("system_role_permissions", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Identity.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_count");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LockoutEndUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end_at");

                    b.Property<string>("LoginName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("login_name");

                    b.Property<bool>("MustChangePassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("must_change_password");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasDefaultValue("vi")
                        .HasColumnName("preferred_language");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_users_employee_id");

                    b.HasIndex("LoginName")
                        .IsUnique()
                        .HasDatabaseName("ix_users_login_name");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Planning.Flight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Aircraft")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("aircraft");

                    b.Property<string>("Belt")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("belt");

                    b.Property<string>("Carry")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("carry");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DayIdx")
                        .HasColumnType("integer")
                        .HasColumnName("day_idx");

                    b.Property<int>("DelayMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("delay_minutes");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("department_code");

                    b.Property<string>("DepartureFlightNo")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("departure_flight_no");

                    b.Property<string>("Eta")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("eta");

                    b.Property<string>("Etd")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("etd");

                    b.Property<string>("FlightNo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("flight_no");

                    b.Property<string>("Gate")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("gate");

                    b.Property<bool>("IsDelayed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_delayed");

                    b.Property<bool>("IsVip")
                        .HasColumnType("boolean")
                        .HasColumnName("is_vip");

                    b.Property<int>("Manning")
                        .HasColumnType("integer")
                        .HasColumnName("manning");

                    b.Property<string>("ManningExplain")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("manning_explain");

                    b.Property<string>("Parking")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("parking");

                    b.Property<string>("Registration")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("registration");

                    b.Property<string>("Remark")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("remark");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("route");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("Sta")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("sta");

                    b.Property<string>("Std")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("std");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VipNote")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("vip_note");

                    b.Property<string>("WeekId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("week_id");

                    b.HasKey("Id")
                        .HasName("pk_flights");

                    b.HasIndex("FlightNo")
                        .HasDatabaseName("ix_flights_flight_no");

                    b.HasIndex("WeekId", "DayIdx")
                        .HasDatabaseName("ix_flights_week_id_day_idx");

                    b.ToTable("flights", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Planning.FlightSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("LockedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_at");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WeekId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("week_id");

                    b.HasKey("Id")
                        .HasName("pk_flight_schedules");

                    b.HasIndex("WeekId")
                        .IsUnique()
                        .HasDatabaseName("ix_flight_schedules_week_id");

                    b.ToTable("flight_schedules", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Planning.NotificationMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("EmployeeId", "IsRead")
                        .HasDatabaseName("ix_notifications_employee_id_is_read");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Planning.ShiftAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("FlightNosJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("flight_nos_json");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<Guid>("ShiftSlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("shift_slot_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_shift_assignments");

                    b.HasIndex("ShiftSlotId", "EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("ix_shift_assignments_shift_slot_id_employee_id");

                    b.ToTable("shift_assignments", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Planning.ShiftRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ByCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("by_code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeltaSegmentsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("delta_segments_json");

                    b.Property<string>("FlightTrigger")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("flight_trigger");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("reason");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<Guid>("ShiftAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("shift_assignment_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_shift_revisions");

                    b.ToTable("shift_revisions", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Planning.ShiftSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BucketKey")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("bucket_key");

                    b.Property<int>("DayIdx")
                        .HasColumnType("integer")
                        .HasColumnName("day_idx");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("department_code");

                    b.Property<string>("FlightNosJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("flight_nos_json");

                    b.Property<int>("Headcount")
                        .HasColumnType("integer")
                        .HasColumnName("headcount");

                    b.Property<string>("SegmentsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("segments_json");

                    b.Property<Guid>("WeeklyPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("weekly_plan_id");

                    b.HasKey("Id")
                        .HasName("pk_shift_slots");

                    b.HasIndex("WeeklyPlanId", "DayIdx", "DepartmentCode")
                        .HasDatabaseName("ix_shift_slots_weekly_plan_id_day_idx_department_code");

                    b.ToTable("shift_slots", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Planning.ShiftSyncProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AffectedJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("affected_json");

                    b.Property<DateTime?>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<Guid?>("ConfirmedByEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("confirmed_by_employee_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DayIdx")
                        .HasColumnType("integer")
                        .HasColumnName("day_idx");

                    b.Property<int>("DelayMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("delay_minutes");

                    b.Property<Guid>("FlightId")
                        .HasColumnType("uuid")
                        .HasColumnName("flight_id");

                    b.Property<string>("FlightNo")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("flight_no");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("summary");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WeekId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("week_id");

                    b.HasKey("Id")
                        .HasName("pk_shift_sync_proposals");

                    b.HasIndex("FlightId", "Status")
                        .HasDatabaseName("ix_shift_sync_proposals_flight_id_status");

                    b.ToTable("shift_sync_proposals", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Planning.WeeklyPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TodayIdx")
                        .HasColumnType("integer")
                        .HasColumnName("today_idx");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WeekDatesJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("week_dates_json");

                    b.Property<string>("WeekId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("week_id");

                    b.Property<int>("WeekYear")
                        .HasColumnType("integer")
                        .HasColumnName("week_year");

                    b.HasKey("Id")
                        .HasName("pk_weekly_plans");

                    b.HasIndex("WeekId")
                        .IsUnique()
                        .HasDatabaseName("ix_weekly_plans_week_id");

                    b.ToTable("weekly_plans", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Identity.Department", b =>
                {
                    b.HasOne("AGS.SmartShift.Domain.Entities.Identity.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_departments_sites_site_id");
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Identity.Employee", b =>
                {
                    b.HasOne("AGS.SmartShift.Domain.Entities.Identity.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employees_departments_department_id");
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Identity.SystemRolePermission", b =>
                {
                    b.HasOne("AGS.SmartShift.Domain.Entities.Identity.SystemPermission", null)
                        .WithMany()
                        .HasForeignKey("PermissionCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_system_role_permissions_system_permissions_permission_code");

                    b.HasOne("AGS.SmartShift.Domain.Entities.Identity.SystemRole", null)
                        .WithMany()
                        .HasForeignKey("RoleCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_system_role_permissions_system_roles_role_code");
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Identity.UserAccount", b =>
                {
                    b.HasOne("AGS.SmartShift.Domain.Entities.Identity.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_employees_employee_id");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Planning.ShiftSlot", b =>
                {
                    b.HasOne("AGS.SmartShift.Domain.Entities.Planning.WeeklyPlan", null)
                        .WithMany("Slots")
                        .HasForeignKey("WeeklyPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shift_slots_weekly_plans_weekly_plan_id");
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Planning.WeeklyPlan", b =>
                {
                    b.Navigation("Slots");
                });
#pragma warning restore 612, 618
        }
    }
}
