// <auto-generated />
using System;
using AGS.SmartShift.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AGS.SmartShift.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SmartShiftDbContext))]
    [Migration("20260521032555_AddStaffingWorkflowEntities")]
    partial class AddStaffingWorkflowEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Attendance.AttendanceGpsPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("AttendanceRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("attendance_record_id");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<double>("Lng")
                        .HasColumnType("double precision")
                        .HasColumnName("lng");

                    b.HasKey("Id")
                        .HasName("pk_attendance_location_samples");

                    b.HasIndex("AttendanceRecordId", "AtUtc")
                        .HasDatabaseName("ix_attendance_location_samples_attendance_record_id_recorded_at");

                    b.ToTable("attendance_location_samples", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Attendance.AttendanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double?>("CheckInLat")
                        .HasColumnType("double precision")
                        .HasColumnName("check_in_lat");

                    b.Property<double?>("CheckInLng")
                        .HasColumnType("double precision")
                        .HasColumnName("check_in_lng");

                    b.Property<DateTime>("CheckInUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_in_at");

                    b.Property<DateTime?>("CheckOutUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_out_at");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double?>("CurrentLat")
                        .HasColumnType("double precision")
                        .HasColumnName("current_lat");

                    b.Property<double?>("CurrentLng")
                        .HasColumnType("double precision")
                        .HasColumnName("current_lng");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<Guid?>("FlightCrewAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("flight_crew_assignment_id");

                    b.Property<string>("GeoNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("geo_note");

                    b.Property<bool>("GeoSimulated")
                        .HasColumnType("boolean")
                        .HasColumnName("geo_simulated");

                    b.Property<bool>("InZone")
                        .HasColumnType("boolean")
                        .HasColumnName("in_zone");

                    b.Property<string>("LateCheckInNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("late_check_in_note");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<Guid?>("ShiftAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("shift_assignment_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_attendance_records");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_attendance_records_employee_id");

                    b.HasIndex("FlightCrewAssignmentId")
                        .HasDatabaseName("ix_attendance_records_flight_crew_assignment_id");

                    b.ToTable("attendance_records", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Attendance.ShiftCheckInPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BucketKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("bucket_key");

                    b.Property<int>("CheckInEarliestMinutesBefore")
                        .HasColumnType("integer")
                        .HasColumnName("check_in_earliest_minutes_before");

                    b.Property<int>("CheckInLatestMinutesAfterStart")
                        .HasColumnType("integer")
                        .HasColumnName("check_in_latest_minutes_after_start");

                    b.Property<int>("CheckOutEarliestMinutesBeforeEnd")
                        .HasColumnType("integer")
                        .HasColumnName("check_out_earliest_minutes_before_end");

                    b.Property<int>("CheckOutLatestMinutesAfterEnd")
                        .HasColumnType("integer")
                        .HasColumnName("check_out_latest_minutes_after_end");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DepartmentCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("department_code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("RequireNoteWhenLate")
                        .HasColumnType("boolean")
                        .HasColumnName("require_note_when_late");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<string>("SegmentEnd")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("segment_end");

                    b.Property<string>("SegmentStart")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("segment_start");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_shift_check_in_policies");

                    b.HasIndex("SiteId", "DepartmentCode", "BucketKey")
                        .IsUnique()
                        .HasDatabaseName("ix_shift_check_in_policies_site_id_department_code_bucket_key");

                    b.ToTable("shift_check_in_policies", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Attendance.WorkZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("PolygonJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("polygon_json");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_work_zones");

                    b.HasIndex("SiteId", "IsActive")
                        .HasDatabaseName("ix_work_zones_site_id_is_active");

                    b.ToTable("work_zones", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Audit.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EmployeeCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("employee_code");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("http_method");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("path");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<Guid?>("UserAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_events");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("ix_audit_events_occurred_at");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Identity.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AllowedRoles")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("allowed_roles_json")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_departments");

                    b.HasIndex("SiteId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_departments_site_id_code");

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Identity.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultSegment")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("default_segment");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uuid")
                        .HasColumnName("manager_id");

                    b.Property<decimal>("MaxWeeklyHours")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)")
                        .HasDefaultValue(48m)
                        .HasColumnName("max_weekly_hours");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("PreferredShiftCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("preferred_shift_code");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_employees");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_employees_code");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_employees_department_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_employees_name");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserAccountId", "ExpiresAtUtc")
                        .HasDatabaseName("ix_refresh_tokens_user_id_expires_at");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Identity.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("timezone");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sites");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_sites_code");

                    b.ToTable("sites", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Identity.SystemPermission", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("module");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameVi")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name_vi");

                    b.HasKey("Code")
                        .HasName("pk_system_permissions");

                    b.ToTable("system_permissions", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Identity.SystemRole", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameVi")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name_vi");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Code")
                        .HasName("pk_system_roles");

                    b.ToTable("system_roles", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Identity.SystemRolePermission", b =>
                {
                    b.Property<string>("RoleCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role_code");

                    b.Property<string>("PermissionCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("permission_code");

                    b.HasKey("RoleCode", "PermissionCode")
                        .HasName("pk_system_role_permissions");

                    b.HasIndex("PermissionCode")
                        .HasDatabaseName("ix_system_role_permissions_permission_code");

                    b.ToTable("system_role_permissions", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Identity.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_count");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LockoutEndUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end_at");

                    b.Property<string>("LoginName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("login_name");

                    b.Property<bool>("MustChangePassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("must_change_password");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasDefaultValue("vi")
                        .HasColumnName("preferred_language");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_users_employee_id");

                    b.HasIndex("LoginName")
                        .IsUnique()
                        .HasDatabaseName("ix_users_login_name");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Leave.LeaveRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateOnly>("FromDate")
                        .HasColumnType("date")
                        .HasColumnName("from_date");

                    b.Property<Guid>("LeaveTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("leave_type_id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateOnly>("ToDate")
                        .HasColumnType("date")
                        .HasColumnName("to_date");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_leave_requests");

                    b.HasIndex("LeaveTypeId")
                        .HasDatabaseName("ix_leave_requests_leave_type_id");

                    b.HasIndex("EmployeeId", "FromDate", "ToDate")
                        .HasDatabaseName("ix_leave_requests_employee_id_from_date_to_date");

                    b.ToTable("leave_requests", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Leave.LeaveType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_leave_types");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_leave_types_code");

                    b.ToTable("leave_types", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Planning.AircraftManningRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AircraftPattern")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("aircraft_pattern");

                    b.Property<int>("BaseManning")
                        .HasColumnType("integer")
                        .HasColumnName("base_manning");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_aircraft_manning_rules");

                    b.ToTable("aircraft_manning_rules", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Planning.AirlineManningRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AirlinePrefix")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("airline_prefix");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal>("Multiplier")
                        .HasColumnType("numeric")
                        .HasColumnName("multiplier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_airline_manning_rules");

                    b.ToTable("airline_manning_rules", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Planning.DailyStaffingBioHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignerEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigner_employee_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DailyStaffingPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("daily_staffing_plan_id");

                    b.Property<Guid?>("EveningSupEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("evening_sup_employee_id");

                    b.Property<Guid?>("MorningSupEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("morning_sup_employee_id");

                    b.Property<string>("RadioNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("radio_note");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_daily_staffing_bio_headers");

                    b.HasIndex("DailyStaffingPlanId")
                        .IsUnique()
                        .HasDatabaseName("uq_daily_staffing_bio_headers_plan_id");

                    b.ToTable("daily_staffing_bio_headers", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Planning.DailyStaffingLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DailyStaffingPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("daily_staffing_plan_id");

                    b.Property<Guid>("FlightId")
                        .HasColumnType("uuid")
                        .HasColumnName("flight_id");

                    b.Property<int>("ProposedManning")
                        .HasColumnType("integer")
                        .HasColumnName("proposed_manning");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<int>("Segment")
                        .HasColumnType("integer")
                        .HasColumnName("segment");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<int>("TargetManning")
                        .HasColumnType("integer")
                        .HasColumnName("target_manning");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_daily_staffing_lines");

                    b.HasIndex("FlightId")
                        .HasDatabaseName("ix_daily_staffing_lines_flight_id");

                    b.HasIndex("DailyStaffingPlanId", "FlightId", "Segment")
                        .IsUnique()
                        .HasDatabaseName("uq_daily_staffing_lines_plan_flight_segment");

                    b.ToTable("daily_staffing_lines", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Planning.DailyStaffingPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DayIdx")
                        .HasColumnType("integer")
                        .HasColumnName("day_idx");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("department_code");

                    b.Property<string>("HeaderJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("header_json");

                    b.Property<string>("LockReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("lock_reason");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<Guid?>("PublishedByEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("published_by");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WeekId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("week_id");

                    b.HasKey("Id")
                        .HasName("pk_daily_staffing_plans");

                    b.HasIndex("SiteId", "WeekId", "DayIdx", "DepartmentCode")
                        .IsUnique()
                        .HasDatabaseName("uq_daily_staffing_plans_site_week_day_dept");

                    b.ToTable("daily_staffing_plans", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Planning.EmployeeDayAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowOvertime")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_overtime");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DayIdx")
                        .HasColumnType("integer")
                        .HasColumnName("day_idx");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WeekId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("week_id");

                    b.HasKey("Id")
                        .HasName("pk_employee_day_availabilities");

                    b.HasIndex("WeekId", "DayIdx", "EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("ix_employee_day_availabilities_week_id_day_idx_employee_id");

                    b.ToTable("employee_day_availabilities", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Planning.EmployeeQualification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CrewRole")
                        .HasColumnType("integer")
                        .HasColumnName("crew_role");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("Proficiency")
                        .HasColumnType("integer")
                        .HasColumnName("proficiency");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<int>("Segment")
                        .HasColumnType("integer")
                        .HasColumnName("segment");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_employee_qualifications");

                    b.HasIndex("EmployeeId", "Segment", "CrewRole")
                        .IsUnique()
                        .HasDatabaseName("uq_employee_qualifications_emp_segment_role");

                    b.ToTable("employee_qualifications", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Planning.Flight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Aircraft")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("aircraft");

                    b.Property<string>("Belt")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("belt");

                    b.Property<string>("Carry")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("carry");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DayIdx")
                        .HasColumnType("integer")
                        .HasColumnName("day_idx");

                    b.Property<int>("DelayMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("delay_minutes");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("department_code");

                    b.Property<string>("DepartureFlightNo")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("departure_flight_no");

                    b.Property<string>("Eta")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("eta");

                    b.Property<int>("EtaDelayMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("eta_delay_minutes");

                    b.Property<string>("Etd")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("etd");

                    b.Property<int>("EtdDelayMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("etd_delay_minutes");

                    b.Property<int>("ExcelRowNo")
                        .HasColumnType("integer")
                        .HasColumnName("excel_row_no");

                    b.Property<string>("FlightNo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("flight_no");

                    b.Property<string>("Gate")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("gate");

                    b.Property<bool>("IsDelayed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_delayed");

                    b.Property<bool>("IsVip")
                        .HasColumnType("boolean")
                        .HasColumnName("is_vip");

                    b.Property<int>("Manning")
                        .HasColumnType("integer")
                        .HasColumnName("manning");

                    b.Property<string>("ManningExplain")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("manning_explain");

                    b.Property<string>("Parking")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("parking");

                    b.Property<string>("Registration")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("registration");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasColumnName("remark");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("route");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Sta")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("sta");

                    b.Property<string>("Std")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("std");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VipNote")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("vip_note");

                    b.Property<string>("WeekId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("week_id");

                    b.HasKey("Id")
                        .HasName("pk_flights");

                    b.HasIndex("FlightNo")
                        .HasDatabaseName("ix_flights_flight_no");

                    b.HasIndex("WeekId", "DayIdx")
                        .HasDatabaseName("ix_flights_week_day");

                    b.HasIndex("WeekId", "DayIdx", "FlightNo")
                        .HasDatabaseName("ix_flights_week_day_flight_no");

                    b.HasIndex("WeekId", "DayIdx", "SortOrder")
                        .HasDatabaseName("ix_flights_week_day_sort");

                    b.ToTable("flights", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Planning.FlightCrewAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsOvertime")
                        .HasColumnType("boolean")
                        .HasColumnName("is_overtime");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("StaffingLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("staffing_line_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<TimeOnly>("WorkEnd")
                        .HasColumnType("time without time zone")
                        .HasColumnName("work_end");

                    b.Property<TimeOnly>("WorkStart")
                        .HasColumnType("time without time zone")
                        .HasColumnName("work_start");

                    b.HasKey("Id")
                        .HasName("pk_flight_crew_assignments");

                    b.HasIndex("StaffingLineId", "EmployeeId", "Role")
                        .HasDatabaseName("ix_flight_crew_assignments_staffing_line_id_employee_id_role");

                    b.ToTable("flight_crew_assignments", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Planning.FlightImportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("DayIdx")
                        .HasColumnType("integer")
                        .HasColumnName("day_idx");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("integer")
                        .HasColumnName("progress_percent");

                    b.Property<string>("ResultJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("result_json");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WeekId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("week_id");

                    b.HasKey("Id")
                        .HasName("pk_flight_import_jobs");

                    b.ToTable("flight_import_jobs", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Planning.FlightSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("LockedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_at");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WeekId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("week_id");

                    b.HasKey("Id")
                        .HasName("pk_flight_schedules");

                    b.HasIndex("WeekId")
                        .IsUnique()
                        .HasDatabaseName("ix_flight_schedules_week_id");

                    b.ToTable("flight_schedules", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Planning.FlightScheduleDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DayIdx")
                        .HasColumnType("integer")
                        .HasColumnName("day_idx");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<string>("SheetRemark")
                        .HasColumnType("text")
                        .HasColumnName("sheet_remark");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("SourceDayLabel")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source_day_label");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WeekId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("week_id");

                    b.HasKey("Id")
                        .HasName("pk_flight_schedule_days");

                    b.HasIndex("WeekId")
                        .HasDatabaseName("ix_flight_schedule_days_week_id");

                    b.HasIndex("WeekId", "DayIdx")
                        .IsUnique()
                        .HasDatabaseName("ux_flight_schedule_days_week_day");

                    b.ToTable("flight_schedule_days", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Planning.NotificationMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("EmployeeId", "IsRead")
                        .HasDatabaseName("ix_notifications_employee_id_is_read");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Planning.ShiftAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("FlightNosJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("flight_nos_json");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<Guid>("ShiftSlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("shift_slot_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_shift_assignments");

                    b.HasIndex("ShiftSlotId", "EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("ix_shift_assignments_shift_slot_id_employee_id");

                    b.ToTable("shift_assignments", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Planning.ShiftRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ByCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("by_code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeltaSegmentsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("delta_segments_json");

                    b.Property<string>("FlightTrigger")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("flight_trigger");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("reason");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<Guid>("ShiftAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("shift_assignment_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_shift_revisions");

                    b.ToTable("shift_revisions", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Planning.ShiftSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BucketKey")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("bucket_key");

                    b.Property<int>("DayIdx")
                        .HasColumnType("integer")
                        .HasColumnName("day_idx");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("department_code");

                    b.Property<string>("FlightNosJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("flight_nos_json");

                    b.Property<int>("Headcount")
                        .HasColumnType("integer")
                        .HasColumnName("headcount");

                    b.Property<string>("SegmentsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("segments_json");

                    b.Property<Guid>("WeeklyPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("weekly_plan_id");

                    b.HasKey("Id")
                        .HasName("pk_shift_slots");

                    b.HasIndex("WeeklyPlanId", "DayIdx", "DepartmentCode")
                        .HasDatabaseName("ix_shift_slots_weekly_plan_id_day_idx_department_code");

                    b.ToTable("shift_slots", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Planning.ShiftSyncProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AffectedJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("affected_json");

                    b.Property<DateTime?>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<Guid?>("ConfirmedByEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("confirmed_by_employee_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DayIdx")
                        .HasColumnType("integer")
                        .HasColumnName("day_idx");

                    b.Property<int>("DelayMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("delay_minutes");

                    b.Property<Guid>("FlightId")
                        .HasColumnType("uuid")
                        .HasColumnName("flight_id");

                    b.Property<string>("FlightNo")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("flight_no");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("summary");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WeekId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("week_id");

                    b.HasKey("Id")
                        .HasName("pk_shift_sync_proposals");

                    b.HasIndex("FlightId", "Status")
                        .HasDatabaseName("ix_shift_sync_proposals_flight_id_status");

                    b.ToTable("shift_sync_proposals", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Planning.ShiftTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("department_code");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsOvernight")
                        .HasColumnType("boolean")
                        .HasColumnName("is_overnight");

                    b.Property<decimal>("MaxHours")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("max_hours");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<int?>("Segment")
                        .HasColumnType("integer")
                        .HasColumnName("segment");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_shift_templates");

                    b.HasIndex("SiteId", "DepartmentCode", "Code")
                        .IsUnique()
                        .HasDatabaseName("uq_shift_templates_site_dept_code");

                    b.ToTable("shift_templates", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Planning.StaffingCrewProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CrewRole")
                        .HasColumnType("integer")
                        .HasColumnName("crew_role");

                    b.Property<Guid>("DailyStaffingPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("daily_staffing_plan_id");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsAutoAssigned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_auto_assigned");

                    b.Property<bool>("IsOvertime")
                        .HasColumnType("boolean")
                        .HasColumnName("is_overtime");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<Guid?>("ShiftTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("shift_template_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("StaffingLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("staffing_line_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<TimeOnly>("WorkEnd")
                        .HasColumnType("time without time zone")
                        .HasColumnName("work_end");

                    b.Property<TimeOnly>("WorkStart")
                        .HasColumnType("time without time zone")
                        .HasColumnName("work_start");

                    b.HasKey("Id")
                        .HasName("pk_staffing_crew_proposals");

                    b.HasIndex("DailyStaffingPlanId")
                        .HasDatabaseName("ix_staffing_crew_proposals_plan_id");

                    b.HasIndex("StaffingLineId")
                        .HasDatabaseName("ix_staffing_crew_proposals_staffing_line_id");

                    b.ToTable("staffing_crew_proposals", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Planning.WeeklyPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TodayIdx")
                        .HasColumnType("integer")
                        .HasColumnName("today_idx");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WeekDatesJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("week_dates_json");

                    b.Property<string>("WeekId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("week_id");

                    b.Property<int>("WeekYear")
                        .HasColumnType("integer")
                        .HasColumnName("week_year");

                    b.HasKey("Id")
                        .HasName("pk_weekly_plans");

                    b.HasIndex("WeekId")
                        .IsUnique()
                        .HasDatabaseName("ix_weekly_plans_week_id");

                    b.ToTable("weekly_plans", (string)null);
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Identity.Department", b =>
                {
                    b.HasOne("AGS.SmartShift.Domain.Entities.Identity.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_departments_sites_site_id");
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Identity.Employee", b =>
                {
                    b.HasOne("AGS.SmartShift.Domain.Entities.Identity.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employees_departments_department_id");
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Identity.SystemRolePermission", b =>
                {
                    b.HasOne("AGS.SmartShift.Domain.Entities.Identity.SystemPermission", null)
                        .WithMany()
                        .HasForeignKey("PermissionCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_system_role_permissions_system_permissions_permission_code");

                    b.HasOne("AGS.SmartShift.Domain.Entities.Identity.SystemRole", null)
                        .WithMany()
                        .HasForeignKey("RoleCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_system_role_permissions_system_roles_role_code");
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Identity.UserAccount", b =>
                {
                    b.HasOne("AGS.SmartShift.Domain.Entities.Identity.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_employees_employee_id");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Leave.LeaveRequest", b =>
                {
                    b.HasOne("AGS.SmartShift.Domain.Entities.Leave.LeaveType", null)
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_leave_requests_leave_types_leave_type_id");
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Planning.DailyStaffingBioHeader", b =>
                {
                    b.HasOne("AGS.SmartShift.Domain.Entities.Planning.DailyStaffingPlan", null)
                        .WithMany()
                        .HasForeignKey("DailyStaffingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_daily_staffing_bio_headers_daily_staffing_plans_daily_staff");
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Planning.DailyStaffingLine", b =>
                {
                    b.HasOne("AGS.SmartShift.Domain.Entities.Planning.DailyStaffingPlan", null)
                        .WithMany()
                        .HasForeignKey("DailyStaffingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_daily_staffing_lines_daily_staffing_plans_daily_staffing_pl");

                    b.HasOne("AGS.SmartShift.Domain.Entities.Planning.Flight", null)
                        .WithMany()
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_daily_staffing_lines_flights_flight_id");
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Planning.FlightCrewAssignment", b =>
                {
                    b.HasOne("AGS.SmartShift.Domain.Entities.Planning.DailyStaffingLine", null)
                        .WithMany()
                        .HasForeignKey("StaffingLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_flight_crew_assignments_daily_staffing_lines_staffing_line_");
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Planning.ShiftSlot", b =>
                {
                    b.HasOne("AGS.SmartShift.Domain.Entities.Planning.WeeklyPlan", null)
                        .WithMany("Slots")
                        .HasForeignKey("WeeklyPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shift_slots_weekly_plans_weekly_plan_id");
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Planning.StaffingCrewProposal", b =>
                {
                    b.HasOne("AGS.SmartShift.Domain.Entities.Planning.DailyStaffingPlan", null)
                        .WithMany()
                        .HasForeignKey("DailyStaffingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_staffing_crew_proposals_daily_staffing_plans_daily_staffing");

                    b.HasOne("AGS.SmartShift.Domain.Entities.Planning.DailyStaffingLine", null)
                        .WithMany()
                        .HasForeignKey("StaffingLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_staffing_crew_proposals_daily_staffing_lines_staffing_line_");
                });

            modelBuilder.Entity("AGS.SmartShift.Domain.Entities.Planning.WeeklyPlan", b =>
                {
                    b.Navigation("Slots");
                });
#pragma warning restore 612, 618
        }
    }
}
