<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AGS.SmartShift.Application\AGS.SmartShift.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\..\..\reference-data\Kế_hoạch_bay.xlsx" LogicalName="Seed.Data.Ke_hoach_bay.xlsx" />
    <EmbeddedResource Include="..\..\..\..\reference-data\PVHK_Di_Lich_phan_cong_theo_ngay.xlsx" LogicalName="Seed.Data.Pvhk_Di_Lich_phan_cong_theo_ngay.xlsx" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" />
    <PackageReference Include="ClosedXML" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="EFCore.NamingConventions" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
  </ItemGroup>

</Project>
