import type { CSSProperties } from "react";
import { agsTokens } from "@/components/theme/tokens";

/** Subset of `mobStyles` from `source-code/combined/AGS_Demo.jsx`. */
export const mobile = {
  screen: {
    minWidth: 0,
  } satisfies CSSProperties,
  title: {
    fontSize: 18,
    fontWeight: 700,
    margin: "0 0 4px",
    color: agsTokens.textBody,
  } satisfies CSSProperties,
  subtitle: {
    fontSize: 12,
    color: "#64748b",
    margin: "0 0 12px",
    lineHeight: 1.45,
  } satisfies CSSProperties,
  card: {
    background: "#fff",
    border: "1px solid #e2e8f0",
    borderRadius: 10,
    padding: 14,
    marginBottom: 10,
  } satisfies CSSProperties,
  bannerWarn: {
    background: "#fef2f2",
    border: "1px solid #fecaca",
    borderRadius: 8,
    padding: "10px 12px",
    fontSize: 12,
    color: "#991b1b",
    marginBottom: 10,
    lineHeight: 1.4,
  } satisfies CSSProperties,
  bannerInfo: {
    background: agsTokens.yellowMutedBg,
    border: `1px solid ${agsTokens.yellowMutedBorder}`,
    borderRadius: 8,
    padding: "10px 12px",
    fontSize: 12,
    color: "#451a03",
    marginBottom: 10,
    lineHeight: 1.4,
  } satisfies CSSProperties,
  btnPrimary: {
    width: "100%",
    padding: "12px 16px",
    border: "none",
    borderRadius: 8,
    background: agsTokens.primary,
    color: agsTokens.primaryOn,
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "inherit",
    marginTop: 8,
  } satisfies CSSProperties,
  btnSecondary: {
    flex: 1,
    padding: "10px 12px",
    border: "1px solid #cbd5e1",
    borderRadius: 8,
    background: "#fff",
    fontSize: 13,
    fontWeight: 500,
    cursor: "pointer",
    fontFamily: "inherit",
  } satisfies CSSProperties,
  btnRow: {
    display: "flex",
    gap: 8,
    marginTop: 8,
  } satisfies CSSProperties,
  miniMetric: {
    background: "#fff",
    border: "1px solid #e2e8f0",
    borderRadius: 8,
    padding: 12,
    textAlign: "center",
  } satisfies CSSProperties,
  teamRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    background: "#fff",
    border: "1px solid #e2e8f0",
    borderRadius: 8,
    padding: 10,
    marginBottom: 8,
  } satisfies CSSProperties,
  teamAvatar: {
    width: 36,
    height: 36,
    borderRadius: "50%",
    background: "#e2e8f0",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 700,
    fontSize: 14,
    color: "#475569",
    flexShrink: 0,
  } satisfies CSSProperties,
  btnSm: {
    padding: "6px 10px",
    border: "1px solid #cbd5e1",
    borderRadius: 6,
    background: "#fff",
    fontSize: 11,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "inherit",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  rqGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 8,
  } satisfies CSSProperties,
  rqBtn: {
    padding: 14,
    border: "1px solid #e2e8f0",
    borderRadius: 8,
    background: "#fff",
    textAlign: "left",
    cursor: "pointer",
    fontFamily: "inherit",
  } satisfies CSSProperties,
  profileSection: {
    background: "#fff",
    border: "1px solid #e2e8f0",
    borderRadius: 8,
    padding: 12,
    marginBottom: 10,
  } satisfies CSSProperties,
  profileRow: {
    display: "flex",
    justifyContent: "space-between",
    fontSize: 13,
    padding: "8px 0",
    borderBottom: "1px solid #f1f5f9",
  } satisfies CSSProperties,
  avatarLg: {
    width: 64,
    height: 64,
    borderRadius: "50%",
    background: agsTokens.primary,
    color: agsTokens.primaryOn,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 700,
    fontSize: 22,
  } satisfies CSSProperties,
};
