import type { CSSProperties } from "react";
import { agsTokens } from "@/components/theme/tokens";

/** AGS web app layout styles (brand-aligned) + `webStyles` in `source-code/combined/AGS_Demo.jsx`. */
export const chrome = {
  page: {
    padding: "32px 40px",
    minWidth: 0,
  } satisfies CSSProperties,
  h1: {
    fontSize: 26,
    fontWeight: 700,
    margin: "0 0 4px",
    letterSpacing: -0.5,
    color: "#0f172a",
  } satisfies CSSProperties,
  h2: {
    fontSize: 16,
    fontWeight: 600,
    margin: "20px 0 12px",
    color: "#0f172a",
  } satisfies CSSProperties,
  subtitle: {
    fontSize: 13,
    color: "#64748b",
    margin: 0,
  } satisfies CSSProperties,
  metricGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))",
    gap: 12,
    marginBottom: 28,
  } satisfies CSSProperties,
  metric: {
    background: "#fff",
    border: "1px solid #e2e8f0",
    borderRadius: 8,
    padding: 16,
  } satisfies CSSProperties,
  stageList: {
    background: "#fff",
    border: "1px solid #e2e8f0",
    borderRadius: 8,
    padding: "8px 0",
    marginBottom: 24,
    position: "relative",
  } satisfies CSSProperties,
  stageItem: {
    display: "flex",
    alignItems: "flex-start",
    gap: 14,
    padding: "16px 20px",
    position: "relative",
  } satisfies CSSProperties,
  quickGuideCard: {
    background: agsTokens.yellowMutedBg,
    border: `1px solid ${agsTokens.yellowMutedBorder}`,
    borderRadius: 8,
    padding: "16px 20px",
    marginTop: 24,
  } satisfies CSSProperties,
  stageNum: {
    width: 32,
    height: 32,
    borderRadius: 100,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 13,
    fontWeight: 700,
    flexShrink: 0,
    zIndex: 2,
  } satisfies CSSProperties,
  stageLine: {
    position: "absolute",
    left: 35,
    top: 48,
    bottom: -16,
    width: 2,
    zIndex: 1,
  } satisfies CSSProperties,
  stageBody: { flex: 1, paddingTop: 4 } satisfies CSSProperties,
  stageTitle: {
    fontSize: 14,
    fontWeight: 600,
    margin: 0,
    color: "#0f172a",
  } satisfies CSSProperties,
  stageActor: {
    fontSize: 10,
    color: "#64748b",
    textTransform: "uppercase",
    letterSpacing: 1,
    fontFamily: "ui-sans-serif, system-ui, -apple-system, sans-serif",
  } satisfies CSSProperties,
  btnPrimary: {
    padding: "9px 18px",
    border: `1px solid ${agsTokens.primary}`,
    background: agsTokens.primary,
    borderRadius: 6,
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    color: agsTokens.primaryOn,
    fontFamily: "inherit",
  } satisfies CSSProperties,
  btnSecondary: {
    padding: "9px 16px",
    border: "1px solid #cbd5e1",
    background: "#fff",
    borderRadius: 6,
    fontSize: 13,
    fontWeight: 500,
    cursor: "pointer",
    color: "#475569",
    fontFamily: "inherit",
  } satisfies CSSProperties,
  linkBtn: {
    fontSize: 12,
    color: agsTokens.primaryHover,
    background: "transparent",
    border: "none",
    cursor: "pointer",
    padding: 0,
    fontWeight: 500,
    fontFamily: "inherit",
  } satisfies CSSProperties,
  input: {
    flex: 1,
    minWidth: 160,
    padding: "8px 12px",
    border: "1px solid #cbd5e1",
    borderRadius: 6,
    fontSize: 13,
    fontFamily: "inherit",
    background: "#fff",
    outline: "none",
    color: "#0f172a",
  } satisfies CSSProperties,
  select: {
    padding: "8px 12px",
    border: "1px solid #cbd5e1",
    borderRadius: 6,
    fontSize: 13,
    fontFamily: "inherit",
    background: "#fff",
    color: "#0f172a",
  } satisfies CSSProperties,
  toolbar: {
    display: "flex",
    gap: 12,
    marginBottom: 16,
    alignItems: "center",
    flexWrap: "wrap",
  } satisfies CSSProperties,
  pastBanner: {
    marginBottom: 16,
    padding: "10px 14px",
    background: "#f1f5f9",
    border: "1px dashed #cbd5e1",
    borderRadius: 8,
    fontSize: 12,
    color: "#475569",
    display: "flex",
    alignItems: "center",
    gap: 8,
  } satisfies CSSProperties,
  infoBanner: {
    marginBottom: 16,
    padding: "10px 14px",
    background: agsTokens.yellowMutedBg,
    border: `1px solid ${agsTokens.yellowMutedBorder}`,
    borderRadius: 8,
    fontSize: 12,
    color: "#451a03",
  } satisfies CSSProperties,
  warnBanner: {
    marginBottom: 16,
    padding: "10px 14px",
    background: "#fffbeb",
    border: "1px solid #fde68a",
    borderRadius: 8,
    fontSize: 12,
    color: "#92400e",
  } satisfies CSSProperties,
  successBanner: {
    marginBottom: 16,
    padding: "10px 14px",
    background: "#f0fdf4",
    border: "1px solid #bbf7d0",
    borderRadius: 8,
    fontSize: 12,
    color: "#166534",
  } satisfies CSSProperties,
  tableWrap: {
    background: "#fff",
    border: "1px solid #e2e8f0",
    borderRadius: 8,
    overflow: "hidden",
  } satisfies CSSProperties,
  dayPill: {
    padding: "8px 16px",
    borderRadius: 6,
    fontSize: 13,
    fontWeight: 500,
    cursor: "pointer",
    border: "1px solid #cbd5e1",
    background: "#fff",
    color: "#475569",
    fontFamily: "inherit",
  } satisfies CSSProperties,
  dayPillActive: {
    border: `1px solid ${agsTokens.primary}`,
    background: agsTokens.primary,
    color: agsTokens.primaryOn,
    fontWeight: 600,
  } satisfies CSSProperties,
  fieldLabel: {
    fontSize: 10,
    color: "#64748b",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 6,
    fontWeight: 600,
  } satisfies CSSProperties,
  emptyState: {
    background: "#fff",
    border: "1px dashed #cbd5e1",
    borderRadius: 8,
    padding: 40,
    textAlign: "center",
    color: "#64748b",
  } satisfies CSSProperties,
  slotCard: {
    background: "#fff",
    border: "1px solid #e2e8f0",
    borderRadius: 8,
    padding: 16,
    marginBottom: 12,
  } satisfies CSSProperties,
  assignmentRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "8px 12px",
    background: "#f8fafc",
    border: "1px solid #e2e8f0",
    borderRadius: 6,
  } satisfies CSSProperties,
  flightChip: {
    padding: "1px 6px",
    borderRadius: 3,
    fontSize: 10,
    fontWeight: 600,
    background: agsTokens.primarySoft,
    color: agsTokens.primary,
  } satisfies CSSProperties,
  acBadge: {
    display: "inline-block",
    padding: "2px 8px",
    borderRadius: 4,
    fontSize: 11,
    fontWeight: 600,
    background: "#f1f5f9",
    color: "#334155",
    border: "1px solid #e2e8f0",
  } satisfies CSSProperties,
  vipBadge: {
    display: "inline-block",
    padding: "2px 8px",
    borderRadius: 4,
    fontSize: 10,
    fontWeight: 600,
    background: "#fef3c7",
    color: "#92400e",
    border: "1px solid #fde68a",
  } satisfies CSSProperties,
  note: {
    fontSize: 12,
    color: "#64748b",
    marginTop: 12,
    lineHeight: 1.5,
  } satisfies CSSProperties,
  addBtn: {
    width: "100%",
    padding: "10px",
    border: "1px dashed #cbd5e1",
    background: "transparent",
    borderRadius: 6,
    fontSize: 12,
    color: "#64748b",
    cursor: "pointer",
    fontFamily: "inherit",
  } satisfies CSSProperties,
  empPicker: {
    background: "#f8fafc",
    border: "1px solid #e2e8f0",
    borderRadius: 6,
    padding: 12,
    marginTop: 8,
  } satisfies CSSProperties,
  empPickerItem: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "8px",
    border: "none",
    background: "#fff",
    borderRadius: 4,
    marginBottom: 4,
    cursor: "pointer",
    fontFamily: "inherit",
    textAlign: "left",
  } satisfies CSSProperties,
  flightsPanel: {
    background: "#fff",
    border: "1px solid #e2e8f0",
    borderRadius: 8,
    maxHeight: 600,
    overflow: "auto",
  } satisfies CSSProperties,
  btnSmGhost: {
    padding: "4px 8px",
    border: "none",
    background: "transparent",
    fontSize: 11,
    fontWeight: 500,
    cursor: "pointer",
    color: "#94a3b8",
    fontFamily: "inherit",
  } satisfies CSSProperties,
  avatarSm: {
    width: 28,
    height: 28,
    borderRadius: 100,
    background: agsTokens.primary,
    color: agsTokens.primaryOn,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 11,
    fontWeight: 700,
    flexShrink: 0,
  } satisfies CSSProperties,
};
